[my_settings]
ping_timeout_secs = 5
cached_to_redis = true

# Node availability information retention period
survival_time_secs = 3600

# this flag act as a human and prevent being banned
anti_banned_as_robot = true

#This variable is available if anti_banned_as_robot is set to true.
request_interval_secs = 1


[default]
template_dir = "static"
address = "0.0.0.0"
port = 8000
workers = 16
keep_alive = 5
ident = "Rocket"
# please change "normal" to "off" when you deploy the web app
log_level = "normal"
temp_dir = "/tmp"
cli_colors = true
## NOTE: Don't (!) use this key! Generate your own!
secret_key = "hPRYyVRiMyxpw5sCC1XeCMN1kFsDCqKvBi2QJxMMQQk="

[default.databases.sqlite_database]
url = "db/db.sqlite"

[default.limits]
forms = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

#[default.tls]
#certs = "/fakesite_cert/chained_cert.pem"
#key = "/fakesite_cert/private_key.pem"

[default.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 5
mercy = 5
